services:
  - type: web
    name: velin-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://devarashettyakhileshroy_db_user:sgWqv0fF4hcX9p9A@cluster0.aslhrvb.mongodb.net/velin
      - key: JWT_SECRET
        value: velin-super-secret-jwt-key-2024
      - key: COMMISSION_RATE
        value: 15
      - key: PAYMENT_MODE
        value: mock